spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 3.34.151.10

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 3.34.151.10

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common

  datasource:
    url: "jdbc:mysql://localhost:3306/umc"
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect